"""Synchronize the verified-main progress ledger and TODO state view.

Completion authority is deliberately narrow: only commits reachable from the
selected protected-main ref are rendered as MERGED.  Phase branches remain
in-flight facts and can never promote themselves by editing documentation.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from hashlib import sha256
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Sequence


ROOT = Path(__file__).resolve().parents[1]
PROGRESS_REL = Path("docs/PROGRESS.md")
TODO_REL = Path("docs/TODO.md")
ANCHOR_RE = re.compile(r"<!-- cs:progress-anchor: ([0-9a-f]{40}) -->")
CURSOR_RE = re.compile(r"<!-- cs:progress-cursor: ([0-9a-f]{40}) -->")
TODO_BLOCK_RE = re.compile(
    r"<!-- cs:state-begin -->\n.*?<!-- cs:state-end -->",
    re.DOTALL,
)


class ProgressStatusError(RuntimeError):
    """A status fact is unavailable, malformed, or inconsistent."""


@dataclass(frozen=True)
class CommitReceipt:
    oid: str
    tree: str
    committed_on: str
    subject: str


@dataclass(frozen=True)
class DerivedStatus:
    progress: str
    todo: str
    verified_main: str
    in_flight: tuple[str, ...]
    appended: int


def _run_git(
    root: Path,
    args: Sequence[str],
    *,
    allow_one: bool = False,
) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(
        ["git", *args],
        cwd=root,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    allowed = {0, 1} if allow_one else {0}
    if completed.returncode not in allowed:
        reason = completed.stderr.strip() or completed.stdout.strip()
        raise ProgressStatusError(
            f"git {' '.join(args)} failed ({completed.returncode}): {reason}"
        )
    return completed


def _resolve_commit(root: Path, ref: str) -> str:
    result = _run_git(root, ["rev-parse", "--verify", f"{ref}^{{commit}}"])
    oid = result.stdout.strip().lower()
    if not re.fullmatch(r"[0-9a-f]{40}", oid):
        raise ProgressStatusError(f"{ref!r} did not resolve to a full commit id")
    return oid


def _is_ancestor(root: Path, ancestor: str, descendant: str) -> bool:
    completed = _run_git(
        root,
        ["merge-base", "--is-ancestor", ancestor, descendant],
        allow_one=True,
    )
    return completed.returncode == 0


def _commit_receipt(root: Path, oid: str) -> CommitReceipt:
    completed = _run_git(
        root,
        ["show", "-s", "--format=%H%x00%T%x00%cs%x00%s", oid],
    )
    fields = completed.stdout.rstrip("\r\n").split("\x00")
    if len(fields) != 4:
        raise ProgressStatusError(f"cannot decode commit metadata for {oid}")
    full_oid, tree, committed_on, subject = fields
    if not re.fullmatch(r"[0-9a-f]{40}", full_oid.lower()):
        raise ProgressStatusError(f"malformed commit id returned for {oid}")
    if not re.fullmatch(r"[0-9a-f]{40}", tree.lower()):
        raise ProgressStatusError(f"malformed tree id returned for {oid}")
    subject = " ".join(subject.split())
    if not subject:
        raise ProgressStatusError(f"commit {oid} has an empty subject")
    return CommitReceipt(
        oid=full_oid.lower(),
        tree=tree.lower(),
        committed_on=committed_on,
        subject=subject,
    )


def _commit_range(root: Path, anchor: str, tip: str) -> list[str]:
    if not _is_ancestor(root, anchor, tip):
        raise ProgressStatusError(
            f"progress anchor {anchor} is not an ancestor of protected main {tip}"
        )
    completed = _run_git(root, ["rev-list", "--reverse", f"{anchor}..{tip}"])
    rest = [line.strip().lower() for line in completed.stdout.splitlines() if line.strip()]
    return [anchor, *rest]


def _progress_header(anchor: str) -> str:
    return (
        "# CodeSkeptic — Verified Progress\n\n"
        "> Generated by `python scripts/progress_status.py sync`. Do not edit\n"
        "> entries by hand. The ledger is append-only and records only commits\n"
        "> reachable from protected main; detailed rationale remains in\n"
        "> `docs/devlog/changelog.md`. History before the bootstrap anchor remains\n"
        "> in that changelog.\n\n"
        f"<!-- cs:progress-anchor: {anchor} -->\n"
    )


def _render_progress(root: Path, anchor: str, tip: str) -> str:
    chunks = [_progress_header(anchor)]
    for oid in _commit_range(root, anchor, tip):
        receipt = _commit_receipt(root, oid)
        chunks.append(
            f"\n## {receipt.committed_on} — {receipt.subject} — MERGED\n\n"
            "+ Protected main contains this transition; no phase branch or prose\n"
            "  record is treated as completion authority.\n"
            f"Evidence: commit `{receipt.oid}`; tree `{receipt.tree}`.\n\n"
            f"<!-- cs:progress-cursor: {receipt.oid} -->\n"
        )
    return "".join(chunks)


def _existing_anchor(progress: str) -> str:
    matches = ANCHOR_RE.findall(progress)
    if len(matches) != 1:
        raise ProgressStatusError(
            "docs/PROGRESS.md must contain exactly one progress anchor"
        )
    cursors = CURSOR_RE.findall(progress)
    if not cursors:
        raise ProgressStatusError("docs/PROGRESS.md has no progress cursor")
    return matches[0]


def _current_branch(root: Path) -> str:
    local = _run_git(root, ["branch", "--show-current"]).stdout.strip()
    if local:
        return local
    for name in ("GITHUB_HEAD_REF", "GITHUB_REF_NAME"):
        value = os.environ.get(name, "").strip()
        if value:
            return value
    raise ProgressStatusError("cannot resolve the current branch name")


def _in_flight_branches(root: Path, main_oid: str) -> tuple[str, ...]:
    completed = _run_git(
        root,
        ["ls-remote", "--heads", "origin", "refs/heads/phase-*"],
    )
    branches: set[str] = set()
    for line in completed.stdout.splitlines():
        parts = line.split()
        if len(parts) != 2 or not parts[1].startswith("refs/heads/phase-"):
            raise ProgressStatusError(f"malformed phase ref from origin: {line!r}")
        oid, ref = parts
        oid = oid.lower()
        if not re.fullmatch(r"[0-9a-f]{40}", oid):
            raise ProgressStatusError(f"malformed phase commit from origin: {line!r}")
        if not _is_ancestor(root, oid, main_oid):
            branches.add(ref.removeprefix("refs/heads/"))
    current = _current_branch(root)
    if current.startswith("phase-"):
        branches.add(current)
    return tuple(sorted(branches))


def _render_state_block(
    root: Path,
    main_oid: str,
    progress: str,
    in_flight: tuple[str, ...],
) -> str:
    merge_base = _run_git(root, ["merge-base", main_oid, "HEAD"]).stdout.strip()
    if not re.fullmatch(r"[0-9a-f]{40}", merge_base.lower()):
        raise ProgressStatusError("cannot resolve the branch/main merge base")
    branch_text = " ".join(in_flight) if in_flight else "none"
    digest = sha256(progress.encode("utf-8")).hexdigest()
    return (
        "<!-- cs:state-begin -->\n"
        "```\n"
        f"base          = {merge_base[:7]}\n"
        f"in_flight     = {branch_text}\n"
        f"verified_main = {main_oid[:7]}\n"
        f"progress      = sha256:{digest}\n"
        "```\n"
        "<!-- cs:state-end -->"
    )


def _replace_todo_state(todo: str, state_block: str) -> str:
    matches = list(TODO_BLOCK_RE.finditer(todo))
    if len(matches) != 1:
        raise ProgressStatusError(
            "docs/TODO.md must contain exactly one generated state block"
        )
    return TODO_BLOCK_RE.sub(state_block, todo, count=1)


def derive_status(root: Path, base_ref: str, *, bootstrap: bool) -> DerivedStatus:
    main_oid = _resolve_commit(root, base_ref)
    progress_path = root / PROGRESS_REL
    todo_path = root / TODO_REL
    if not todo_path.is_file():
        raise ProgressStatusError(f"missing {TODO_REL.as_posix()}")
    todo = todo_path.read_text(encoding="utf-8")

    old_progress = ""
    if progress_path.is_file():
        old_progress = progress_path.read_text(encoding="utf-8")
        anchor = _existing_anchor(old_progress)
    elif bootstrap:
        anchor = main_oid
    else:
        raise ProgressStatusError(f"missing {PROGRESS_REL.as_posix()}; run sync")

    progress = _render_progress(root, anchor, main_oid)
    if old_progress and not progress.startswith(old_progress):
        # Re-rendering through the old cursor must reproduce every existing
        # byte. A mismatch is either history rewriting or manual ledger edits.
        raise ProgressStatusError(
            "docs/PROGRESS.md is not an append-only rendering of protected main"
        )
    old_cursors = CURSOR_RE.findall(old_progress)
    new_cursors = CURSOR_RE.findall(progress)
    appended = len(new_cursors) - len(old_cursors)
    in_flight = _in_flight_branches(root, main_oid)
    state_block = _render_state_block(root, main_oid, progress, in_flight)
    expected_todo = _replace_todo_state(todo, state_block)
    return DerivedStatus(
        progress=progress,
        todo=expected_todo,
        verified_main=main_oid,
        in_flight=in_flight,
        appended=appended,
    )


def _write_atomic(path: Path, content: str) -> None:
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    os.replace(temporary, path)


def sync_repository(root: Path, base_ref: str) -> DerivedStatus:
    status = derive_status(root, base_ref, bootstrap=True)
    _write_atomic(root / PROGRESS_REL, status.progress)
    _write_atomic(root / TODO_REL, status.todo)
    return status


def check_repository(root: Path, base_ref: str) -> DerivedStatus:
    status = derive_status(root, base_ref, bootstrap=False)
    progress = (root / PROGRESS_REL).read_text(encoding="utf-8")
    todo = (root / TODO_REL).read_text(encoding="utf-8")
    if progress != status.progress:
        raise ProgressStatusError(
            "docs/PROGRESS.md is stale; run progress_status.py sync"
        )
    if todo != status.todo:
        raise ProgressStatusError(
            "docs/TODO.md state block is stale; run progress_status.py sync"
        )
    return status


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Synchronize verified protected-main progress and TODO state."
    )
    parser.add_argument("command", choices=("sync", "check"))
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--base-ref", default="origin/main")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    root = arguments.root.resolve()
    try:
        if arguments.command == "sync":
            status = sync_repository(root, arguments.base_ref)
        else:
            status = check_repository(root, arguments.base_ref)
        branches = " ".join(status.in_flight) if status.in_flight else "none"
        print(
            "progress synchronized: "
            f"verified_main={status.verified_main[:7]} "
            f"appended={status.appended} in_flight={branches}"
        )
    except (OSError, ProgressStatusError) as error:
        print(f"progress status error: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
